# works for everything except py37 and pypy3
language: python
matrix:
  include:
  - python: 3.6
    env:
      TOXENV: py26
  - python: 3.6
    env:
      TOXENV: py27
  - python: 3.6
    env:
      TOXENV: py32
  - python: 3.4
    env:
      TOXENV: py34
  - python: 3.5
    env:
      TOXENV: py35
  - python: 3.6
    env:
      TOXENV: py36
  - python: 3.7
    dist: xenial
    env:
      TOXENV: py37
  - python: pypy
    env:
      TOXENV: pypy
# pipenv incompatible with pypy3
# https://github.com/pypa/pipenv/issues/3313
#  - python: pypy3.5
#    env:
#      TOXENV: pypy3
  - python: 3.6
    env:
      TOXENV: jython

before_install:
  - |
    if [ "$JYTHON" == "true" ]; then 
      hg clone http://hg.python.org/jython; cd jython; ant; cd ..; chmod +x "$(pwd)/jython/dist/bin/jython"
      export PYTHON_EXE="$(pwd)/jython/dist/bin/jython"; else export PYTHON_EXE=python
      alias jython="$(pwd)/jython/dist/bin/jython"
      export PATH="$(pwd)/jython/dist/bin:$PATH"; fi
      wget https://bootstrap.pypa.io/get-pip.py
      $PYTHON_EXE get-pip.py
    fi
  - uname -a
  - lsb_release -a
install:
  - $PYTHON_EXE -m pip install --upgrade pip tox
script:	python -m tox -e $TOXENV
