# works for everything except py37 and pypy3
language: python
matrix:
  include:
  - python: 3.6
    env:
      TOXENV: py26
  - python: 3.6
    env:
      TOXENV: py27
  - python: 3.6
    env:
      TOXENV: py32
  - python: 3.4
    env:
      TOXENV: py34
  - python: 3.5
    env:
      TOXENV: py35
  - python: 3.6
    env:
      TOXENV: py36
  - python: 3.7
    dist: xenial
    env:
      TOXENV: py37
  - python: pypy
    env:
      TOXENV: pypy
# pipenv incompatible with pypy3
# https://github.com/pypa/pipenv/issues/3313
#  - python: pypy3.5
#    env:
#      TOXENV: pypy3
  - python: 3.6
    env:
      TOXENV: jython


before_install: if [ "$TOXENV" == "jython" ]; then sudo apt-get install jython; fi
install: pip install tox
script: tox
