language: python
python: 3.6
env:
  matrix:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py32
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=py36
    - TOXENV=py37
    - TOXENV=pypy
    - TOXENV=pypy3
    - TOXENV=jython
install: pip install tox
script: tox
