language: python
matrix:
  - python: 2.6
    TOXENV: py26
  - python: 2.7
    TOXENV: py27
  - python: 3.2
    TOXENV: py32
  - python: 3.4
    TOXENV: py34
  - python: 3.5
    TOXENV: py35
  - python: 3.6
    TOXENV: py36
  - python: 3.7
    TOXENV: py37
  - python: pypy
    TOXENV: pypy
  - python: pypy3.5
    TOXENV: pypy3
  - python: 3.6
    TOXENV: jython

before_install: if [ "$TOXENV" == "jython" ]; then sudo apt-get install jython; fi
install: pip install tox
script: tox
